### ISSUE TITLE
Highlight tooltips

### ISSUE THREAD

**Issue by Qusic** [facebooknuclide/hyperclick#11]
I am maintaining a package [atom-youcompleteme](https://github.com/Qusic/atom-youcompleteme) that supports go-to actions with hyperclick.

It would be very useful that when <cmd> or <alt> is held and some text under the mouse is underlined, a tooltip can be shown to indicate the inferred type of a value, the parent of a class, or anything else.

Thanks!

**Comment by hansonw** [comment]
Try the 'datatip' feature in https://atom.io/packages/atom-ide-ui instead :)

Example: https://github.com/jgebhardt/atom-github-user-datatip
