### ISSUE TITLE
Hyperclick 0.1.1 is not working 

### ISSUE THREAD

**Issue by sreeram514** [facebooknuclide/hyperclick#18]
Atom version used is 1.19.0-beta2. 

Goto definition usecase is not working. Even hyperlink is not shown when mouse is hovered.

**Comment by hansonw** [comment]
It's possible that your keybinding has changed. Also, which Hyperclick provider(s) are you using?

<img width="433" alt="screen shot 2017-07-04 at 12 24 24 pm" src="https://user-images.githubusercontent.com/577378/27841291-e3ff894e-60b4-11e7-98e1-abbf6a51e2f1.png">

**Comment by hansonw** [comment]
Can you try the resolution in #20 (remove hyperclick from ~/.atom/.apm, uninstall hyperclick, and reinstall)? Reopen the other thread if that doesn't work.
