### ISSUE TITLE
Lost ctrl+click after update to 0.1.1

### ISSUE THREAD

**Issue by jatubio** [facebooknuclide/hyperclick#19]
On version 0.0.40 i can use 'Ctrl+Click' to underline the word under the mouse and click to go to definition.

On never version i have lost 'Settings' screen to set keybinding. And if i use 'Alt+Click', it does not work correctly. By pressing Alt, the underlined word is most of time two or three words to the right of mouse, not the word under the mouse. Adding the disadvantage of switching between 'Show and Hide' the top menu.

I have installed again the 0.0.40 version

**Comment by manyeung** [comment]
Meet the same issue in version 0.1.1.

I installed back to 0.1.0.

Windows 7
Atom 1.18.0 ia32

**Comment by hansonw** [comment]
I'm still able to find a settings pane. @jatubio what Atom version are you using?

![screen shot 2017-07-04 at 12 28 15 pm](https://user-images.githubusercontent.com/577378/27841210-46392206-60b4-11e7-8ac7-17e1dc2b2587.png)

**Comment by hansonw** [comment]
Can you try the resolution in https://github.com/facebooknuclide/hyperclick/issues/20 (remove hyperclick from ~/.atom/.apm, uninstall hyperclick, and reinstall)?

**Comment by hansonw** [comment]
Closing in favor of #20.

**Comment by jatubio** [comment]
Hi, i have upgraded from 0.0.40 to 0.1.2 and it's working. Not issues.

Sorry for the delayed response
