### ISSUE TITLE
Can't confirm cursor when target selected from left to right

### ISSUE THREAD

**Issue by emil14** [facebooknuclide/hyperclick#21]
Software: Ubuntu 16.04, Atom 1.17.2, Hyperclick 0.1.1
Reproduce: select target with keyboard or mouse and try go to definition by keyboard shortcut, mouse or command-line. it works only if target was selectr from right to left.

The problem is especially relevant for those who do not want to use the mouse.
P.S - I came across this problem when using Hyperclick with Hyperclick JavaScript provider.

**Comment by hansonw** [comment]
This is actually fixed in Nuclide master - I'll do a new release today to get it out :)

**Comment by hansonw** [comment]
Just published v0.1.2. Please reopen if it's still not working correctly and I'll dig further

**Comment by emil14** [comment]
@hansonw thank you for reaction. Looks like it works for mouse click but not for keyboard shortcut.

Ubuntu 16.04, Atom 1.17.2, Hyperclick 0.1.2
