### ISSUE TITLE
Not work in macos Atom with version 1.18.0

### ISSUE THREAD

**Issue by AlbertXiebnu** [facebooknuclide/hyperclick#28]
when press cmd and hold it then click on any functions define in files seems not work at all. Is there any configuration to be done before it actually works?

**Comment by shushz** [comment]
Yes there is a configuration that needs to be done and it depends strongly on the language that you're using.
Please read the languages section docs at https://nuclide.io/docs for your language.

**Comment by AlbertXiebnu** [comment]
@shushz Problems has solved after I install nuclide instead of hyperclick alone. Surprised by nuclide with many useful features, Many thanks for this great work!
