### ISSUE TITLE
hyperclick not work

### ISSUE THREAD

**Issue by zzgzhang** [facebooknuclide/hyperclick#37]
I have hyperclick and js-hyperclick both installed in my atom1.19.5 mac10.12 for nodejs.
hyperclick package is actived but not work.
I have the package-list below.pls help find any conflict if exists. Thanks.
Poor English expression, sorry.

Built-in Atom Packages (79)
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.5
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.4-1
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.6
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.250.0
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.1
├── tabs@0.107.0
├── timecop@0.36.0
├── tree-view@0.217.2
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.4
├── language-gfm@0.89.1
├── language-git@0.19.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-hyperlink@0.16.1
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.39.0
├── language-property-list@0.9.1
├── language-python@0.45.3
├── language-ruby@0.71.1
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.1
├── language-source@0.9.0
├── language-sql@0.25.6
├── language-text@0.7.3
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.1
└── language-yaml@0.30.0

Community Packages (15) /~~~/.atom/packages
├── atom-beautify@0.30.5
├── atom-pigments@0.40.2
├── atom-script@3.15.0
├── atom-ternjs@0.18.3
├── browser-plus@0.0.98
├── busy-signal@1.4.3
├── docblockr@0.11.0
├── highlight-selected@0.13.1
├── hyperclick@0.1.3
├── intentions@1.1.5
├── js-hyperclick@1.11.0
├── linter@2.2.0
├── linter-jshint@3.1.5
├── linter-ui-default@1.6.8
└── minimap@4.29.6

**Comment by hansonw** [comment]
Can you try clearing the APM cache and re-installing the package? Instructions here: https://github.com/facebooknuclide/hyperclick/issues/20#issuecomment-312954082

**Comment by zzgzhang** [comment]
@hansonw Thanks for relay.APM cache cleared(git clone to packaged and cd hyperclick && npm install ) and re-installed the package still not work.
And I removed all my packages but re-installing the hyperclick package.

Follwoing is my install log, if any help.
==================================================================
zzg-mbp:packages zzg$ git clone https://github.com/facebooknuclide/hyperclick.git
Cloning into 'hyperclick'...
remote: Counting objects: 316, done.
remote: Total 316 (delta 0), reused 0 (delta 0), pack-reused 316
Receiving objects: 100% (316/316), 394.76 KiB | 67.00 KiB/s, done.
Resolving deltas: 100% (171/171), done.
zzg-mbp:packages zzg$ cd hyperclick/
zzg-mbp:hyperclick zzg$ npm install
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN prefer global marked@0.3.6 should be installed with -g

> fsevents@1.1.2 install /Users/zzg/.atom/packages/hyperclick/node_modules/fsevents
> node install

[fsevents] Success: "/Users/zzg/.atom/packages/hyperclick/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/zzg/.atom/packages/hyperclick/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> preact@8.2.5 postinstall /Users/zzg/.atom/packages/hyperclick/node_modules/preact
> node -e "console.log('\u001b[35m\u001b[1mLove Preact? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/preact/donate\u001b[0m')"

Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate
hyperclick@0.1.3 /Users/zzg/.atom/packages/hyperclick
├─┬ atom-ide-ui@0.1.9 
│ ├── async-to-generator@1.1.0 
│ ├── classnames@2.2.5 
│ ├── fuzzaldrin-plus@0.4.1 
│ ├── idx@1.2.0 
│ ├─┬ log4js@1.1.1 
│ │ ├─┬ debug@2.6.8 
│ │ │ └── ms@2.0.0 
│ │ └─┬ streamroller@0.4.1 
│ │   ├── date-format@0.0.0 
│ │   ├── debug@0.7.4 
│ │   └─┬ readable-stream@1.1.14 
│ │     └── isarray@0.0.1 
│ ├── marked@0.3.6 
│ ├─┬ nuclide-commons@0.1.9 
│ │ ├── event-kit@2.2.0 
│ │ ├─┬ fs-plus@2.9.3 
│ │ │ ├── async@0.2.10 
│ │ │ ├── mkdirp@0.3.5 
│ │ │ ├── rimraf@2.2.8 
│ │ │ └─┬ underscore-plus@1.6.6 
│ │ │   └── underscore@1.6.0 
│ │ ├─┬ glob@7.1.1 
│ │ │ ├── fs.realpath@1.0.0 
│ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ └── wrappy@1.0.2 
│ │ │ ├── inherits@2.0.3 
│ │ │ └── once@1.4.0 
│ │ ├─┬ lru-cache@4.0.2 
│ │ │ ├── pseudomap@1.0.2 
│ │ │ └── yallist@2.1.2 
│ │ ├── rimraf@2.5.4 
│ │ ├─┬ shell-quote@1.6.1 
│ │ │ ├── array-filter@0.0.1 
│ │ │ ├── array-map@0.0.0 
│ │ │ ├── array-reduce@0.0.0 
│ │ │ └── jsonify@0.0.0 
│ │ └─┬ temp@0.8.3 
│ │   ├── os-tmpdir@1.0.2 
│ │   └── rimraf@2.2.8 
│ ├─┬ nuclide-commons-atom@0.1.9 
│ │ └─┬ shallowequal@0.2.2 
│ │   └─┬ lodash.keys@3.1.2 
│ │     ├── lodash._getnative@3.9.1 
│ │     ├── lodash.isarguments@3.1.0 
│ │     └── lodash.isarray@3.0.4 
│ ├── nuclide-commons-ui@0.1.9 
│ ├─┬ react@15.3.1 
│ │ ├─┬ fbjs@0.8.14 
│ │ │ ├── core-js@1.2.7 
│ │ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ │ ├─┬ node-fetch@1.7.2 
│ │ │ │ │ └─┬ encoding@0.1.12 
│ │ │ │ │   └── iconv-lite@0.4.18 
│ │ │ │ └── whatwg-fetch@2.0.3 
│ │ │ ├─┬ promise@7.3.1 
│ │ │ │ └── asap@2.0.6 
│ │ │ ├── setimmediate@1.0.5 
│ │ │ └── ua-parser-js@0.7.14 
│ │ ├─┬ loose-envify@1.3.1 
│ │ │ └── js-tokens@3.0.2 
│ │ └── object-assign@4.1.1 
│ ├── react-dom@15.3.1 
│ ├─┬ rxjs@5.3.1 
│ │ └── symbol-observable@1.0.4 
│ └── semver@5.3.0 
├─┬ babili-webpack-plugin@0.1.2 
│ ├─┬ babel-core@6.26.0 
│ │ ├─┬ babel-code-frame@6.26.0 
│ │ │ ├─┬ chalk@1.1.3 
│ │ │ │ ├── ansi-styles@2.2.1 
│ │ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ │ ├── has-ansi@2.0.0 
│ │ │ │ └── supports-color@2.0.0 
│ │ │ └── esutils@2.0.2 
│ │ ├─┬ babel-generator@6.26.0 
│ │ │ ├─┬ detect-indent@4.0.0 
│ │ │ │ └─┬ repeating@2.0.1 
│ │ │ │   └── is-finite@1.0.2 
│ │ │ ├── jsesc@1.3.0 
│ │ │ └── trim-right@1.0.1 
│ │ ├── babel-helpers@6.24.1 
│ │ ├── babel-messages@6.23.0 
│ │ ├─┬ babel-register@6.26.0 
│ │ │ ├── core-js@2.5.1 
│ │ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ │ └── os-homedir@1.0.2 
│ │ │ └── source-map-support@0.4.17 
│ │ ├─┬ babel-runtime@6.26.0 
│ │ │ ├── core-js@2.5.1 
│ │ │ └── regenerator-runtime@0.11.0 
│ │ ├── babel-template@6.26.0 
│ │ ├─┬ babel-traverse@6.26.0 
│ │ │ └── globals@9.18.0 
│ │ ├─┬ babel-types@6.26.0 
│ │ │ └── to-fast-properties@1.0.3 
│ │ ├── babylon@6.18.0 
│ │ ├── convert-source-map@1.5.0 
│ │ ├── lodash@4.17.4 
│ │ ├─┬ minimatch@3.0.4 
│ │ │ └─┬ brace-expansion@1.1.8 
│ │ │   ├── balanced-match@1.0.0 
│ │ │   └── concat-map@0.0.1 
│ │ ├── path-is-absolute@1.0.1 
│ │ ├── private@0.1.7 
│ │ └── slash@1.0.0 
│ ├─┬ babel-preset-babili@0.1.4 
│ │ ├─┬ babel-plugin-minify-builtins@0.1.3 
│ │ │ └── babel-helper-evaluate-path@0.1.0 
│ │ ├── babel-plugin-minify-constant-folding@0.1.3 
│ │ ├─┬ babel-plugin-minify-dead-code-elimination@0.1.7 
│ │ │ ├── babel-helper-mark-eval-scopes@0.1.1 
│ │ │ ├── babel-helper-remove-or-void@0.1.1 
│ │ │ └── lodash.some@4.6.0 
│ │ ├─┬ babel-plugin-minify-flip-comparisons@0.1.2 
│ │ │ └── babel-helper-is-void-0@0.1.1 
│ │ ├─┬ babel-plugin-minify-guarded-expressions@0.1.2 
│ │ │ └── babel-helper-flip-expressions@0.1.2 
│ │ ├── babel-plugin-minify-infinity@0.1.2 
│ │ ├── babel-plugin-minify-mangle-names@0.1.3 
│ │ ├── babel-plugin-minify-numeric-literals@0.1.1 
│ │ ├── babel-plugin-minify-replace@0.1.2 
│ │ ├─┬ babel-plugin-minify-simplify@0.1.2 
│ │ │ ├── babel-helper-is-nodes-equiv@0.0.1 
│ │ │ └── babel-helper-to-multiple-sequence-expressions@0.1.1 
│ │ ├── babel-plugin-minify-type-constructors@0.1.2 
│ │ ├── babel-plugin-transform-inline-consecutive-adds@0.1.2 
│ │ ├── babel-plugin-transform-member-expression-literals@6.8.5 
│ │ ├── babel-plugin-transform-merge-sibling-variables@6.8.6 
│ │ ├── babel-plugin-transform-minify-booleans@6.8.3 
│ │ ├── babel-plugin-transform-property-literals@6.8.5 
│ │ ├── babel-plugin-transform-regexp-constructors@0.1.1 
│ │ ├── babel-plugin-transform-remove-console@6.8.5 
│ │ ├── babel-plugin-transform-remove-debugger@6.8.5 
│ │ ├── babel-plugin-transform-remove-undefined@0.1.2 
│ │ ├── babel-plugin-transform-simplify-comparison-operators@6.8.5 
│ │ ├── babel-plugin-transform-undefined-to-void@6.8.3 
│ │ └── lodash.isplainobject@4.0.6 
│ └─┬ webpack-sources@1.0.1 
│   └── source-list-map@2.0.0 
├── preact@8.2.5 
├─┬ preact-compat@3.17.0 
│ ├─┬ immutability-helper@2.3.1 
│ │ └── invariant@2.2.2 
│ ├─┬ preact-render-to-string@3.6.3 
│ │ └── pretty-format@3.8.0 
│ ├── preact-transition-group@1.1.1 
│ ├── prop-types@15.5.10 
│ └── standalone-react-addons-pure-render-mixin@0.1.1 
└─┬ webpack@3.5.5 
  ├── acorn@5.1.2 
  ├─┬ acorn-dynamic-import@2.0.2 
  │ └── acorn@4.0.13 
  ├─┬ ajv@5.2.2 
  │ ├── co@4.6.0 
  │ ├── fast-deep-equal@1.0.0 
  │ ├── json-schema-traverse@0.3.1 
  │ └── json-stable-stringify@1.0.1 
  ├── ajv-keywords@2.1.0 
  ├── async@2.5.0 
  ├─┬ enhanced-resolve@3.4.1 
  │ └── graceful-fs@4.1.11 
  ├─┬ escope@3.6.0 
  │ ├─┬ es6-map@0.1.5 
  │ │ ├── d@1.0.0 
  │ │ ├── es5-ext@0.10.30 
  │ │ ├── es6-iterator@2.0.1 
  │ │ ├── es6-set@0.1.5 
  │ │ ├── es6-symbol@3.1.1 
  │ │ └── event-emitter@0.3.5 
  │ ├── es6-weak-map@2.0.2 
  │ ├── esrecurse@4.2.0 
  │ └── estraverse@4.2.0 
  ├── interpret@1.0.3 
  ├── json-loader@0.5.7 
  ├── json5@0.5.1 
  ├── loader-runner@2.3.0 
  ├─┬ loader-utils@1.1.0 
  │ ├── big.js@3.1.3 
  │ └── emojis-list@2.1.0 
  ├─┬ memory-fs@0.4.1 
  │ ├─┬ errno@0.1.4 
  │ │ └── prr@0.0.0 
  │ └─┬ readable-stream@2.3.3 
  │   ├── core-util-is@1.0.2 
  │   ├── isarray@1.0.0 
  │   ├── process-nextick-args@1.0.7 
  │   ├── safe-buffer@5.1.1 
  │   ├── string_decoder@1.0.3 
  │   └── util-deprecate@1.0.2 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├─┬ node-libs-browser@2.0.0 
  │ ├── assert@1.4.1 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.9 
  │ ├─┬ buffer@4.9.1 
  │ │ ├── base64-js@1.2.1 
  │ │ ├── ieee754@1.1.8 
  │ │ └── isarray@1.0.0 
  │ ├─┬ console-browserify@1.1.0 
  │ │ └── date-now@0.1.4 
  │ ├── constants-browserify@1.0.0 
  │ ├─┬ crypto-browserify@3.11.1 
  │ │ ├─┬ browserify-cipher@1.0.0 
  │ │ │ ├─┬ browserify-aes@1.0.8 
  │ │ │ │ └── buffer-xor@1.0.3 
  │ │ │ ├─┬ browserify-des@1.0.0 
  │ │ │ │ └── des.js@1.0.0 
  │ │ │ └─┬ evp_bytestokey@1.0.3 
  │ │ │   └─┬ md5.js@1.3.4 
  │ │ │     └── hash-base@3.0.4 
  │ │ ├─┬ browserify-sign@4.0.4 
  │ │ │ ├── bn.js@4.11.8 
  │ │ │ ├── browserify-rsa@4.0.1 
  │ │ │ ├─┬ elliptic@6.4.0 
  │ │ │ │ ├── brorand@1.1.0 
  │ │ │ │ ├── hash.js@1.1.3 
  │ │ │ │ ├── hmac-drbg@1.0.1 
  │ │ │ │ ├── minimalistic-assert@1.0.0 
  │ │ │ │ └── minimalistic-crypto-utils@1.0.1 
  │ │ │ └─┬ parse-asn1@5.1.0 
  │ │ │   └── asn1.js@4.9.1 
  │ │ ├── create-ecdh@4.0.0 
  │ │ ├─┬ create-hash@1.1.3 
  │ │ │ ├── cipher-base@1.0.4 
  │ │ │ ├─┬ ripemd160@2.0.1 
  │ │ │ │ └── hash-base@2.0.2 
  │ │ │ └── sha.js@2.4.8 
  │ │ ├── create-hmac@1.1.6 
  │ │ ├─┬ diffie-hellman@5.0.2 
  │ │ │ └── miller-rabin@4.0.0 
  │ │ ├── pbkdf2@3.0.13 
  │ │ ├── public-encrypt@4.0.0 
  │ │ └── randombytes@2.0.5 
  │ ├── domain-browser@1.1.7 
  │ ├── events@1.1.1 
  │ ├── https-browserify@0.0.1 
  │ ├── os-browserify@0.2.1 
  │ ├── path-browserify@0.0.0 
  │ ├── process@0.11.10 
  │ ├── punycode@1.4.1 
  │ ├── querystring-es3@0.2.1 
  │ ├─┬ readable-stream@2.3.3 
  │ │ ├── isarray@1.0.0 
  │ │ └── string_decoder@1.0.3 
  │ ├─┬ stream-browserify@2.0.1 
  │ │ └─┬ readable-stream@2.3.3 
  │ │   ├── isarray@1.0.0 
  │ │   └── string_decoder@1.0.3 
  │ ├─┬ stream-http@2.7.2 
  │ │ ├── builtin-status-codes@3.0.0 
  │ │ ├─┬ readable-stream@2.3.3 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ └── string_decoder@1.0.3 
  │ │ ├── to-arraybuffer@1.0.1 
  │ │ └── xtend@4.0.1 
  │ ├── string_decoder@0.10.31 
  │ ├── timers-browserify@2.0.4 
  │ ├── tty-browserify@0.0.0 
  │ ├─┬ url@0.11.0 
  │ │ ├── punycode@1.3.2 
  │ │ └── querystring@0.2.0 
  │ ├─┬ util@0.10.3 
  │ │ └── inherits@2.0.1 
  │ └─┬ vm-browserify@0.0.4 
  │   └── indexof@0.0.1 
  ├── source-map@0.5.7 
  ├─┬ supports-color@4.4.0 
  │ └── has-flag@2.0.0 
  ├── tapable@0.2.8 
  ├─┬ uglifyjs-webpack-plugin@0.4.6 
  │ └─┬ uglify-js@2.8.29 
  │   ├── uglify-to-browserify@1.0.2 
  │   └─┬ yargs@3.10.0 
  │     ├── camelcase@1.2.1 
  │     ├─┬ cliui@2.1.0 
  │     │ ├─┬ center-align@0.1.3 
  │     │ │ ├─┬ align-text@0.1.4 
  │     │ │ │ ├── longest@1.0.1 
  │     │ │ │ └── repeat-string@1.6.1 
  │     │ │ └── lazy-cache@1.0.4 
  │     │ ├── right-align@0.1.3 
  │     │ └── wordwrap@0.0.2 
  │     └── window-size@0.1.0 
  ├─┬ watchpack@1.4.0 
  │ ├── async@2.5.0 
  │ └─┬ chokidar@1.7.0 
  │   ├─┬ anymatch@1.3.2 
  │   │ ├─┬ micromatch@2.3.11 
  │   │ │ ├─┬ arr-diff@2.0.0 
  │   │ │ │ └── arr-flatten@1.1.0 
  │   │ │ ├── array-unique@0.2.1 
  │   │ │ ├─┬ braces@1.8.5 
  │   │ │ │ ├─┬ expand-range@1.8.2 
  │   │ │ │ │ └─┬ fill-range@2.2.3 
  │   │ │ │ │   ├── is-number@2.1.0 
  │   │ │ │ │   ├─┬ isobject@2.1.0 
  │   │ │ │ │   │ └── isarray@1.0.0 
  │   │ │ │ │   └─┬ randomatic@1.1.7 
  │   │ │ │ │     ├─┬ is-number@3.0.0 
  │   │ │ │ │     │ └── kind-of@3.2.2 
  │   │ │ │ │     └── kind-of@4.0.0 
  │   │ │ │ ├── preserve@0.2.0 
  │   │ │ │ └── repeat-element@1.1.2 
  │   │ │ ├─┬ expand-brackets@0.1.5 
  │   │ │ │ └── is-posix-bracket@0.1.1 
  │   │ │ ├── extglob@0.3.2 
  │   │ │ ├── filename-regex@2.0.1 
  │   │ │ ├─┬ kind-of@3.2.2 
  │   │ │ │ └── is-buffer@1.1.5 
  │   │ │ ├─┬ object.omit@2.0.1 
  │   │ │ │ ├─┬ for-own@0.1.5 
  │   │ │ │ │ └── for-in@1.0.2 
  │   │ │ │ └── is-extendable@0.1.1 
  │   │ │ ├─┬ parse-glob@3.0.4 
  │   │ │ │ ├── glob-base@0.3.0 
  │   │ │ │ └── is-dotfile@1.0.3 
  │   │ │ └─┬ regex-cache@0.4.4 
  │   │ │   └─┬ is-equal-shallow@0.1.3 
  │   │ │     └── is-primitive@2.0.0 
  │   │ └─┬ normalize-path@2.1.1 
  │   │   └── remove-trailing-separator@1.1.0 
  │   ├── async-each@1.0.1 
  │   ├─┬ fsevents@1.1.2 
  │   │ ├── nan@2.7.0 
  │   │ └─┬ node-pre-gyp@0.6.36 
  │   │   ├─┬ mkdirp@0.5.1 
  │   │   │ └── minimist@0.0.8 
  │   │   ├─┬ nopt@4.0.1 
  │   │   │ ├── abbrev@1.1.0 
  │   │   │ └─┬ osenv@0.1.4 
  │   │   │   ├── os-homedir@1.0.2 
  │   │   │   └── os-tmpdir@1.0.2 
  │   │   ├─┬ npmlog@4.1.0 
  │   │   │ ├─┬ are-we-there-yet@1.1.4 
  │   │   │ │ └── delegates@1.0.0 
  │   │   │ ├── console-control-strings@1.1.0 
  │   │   │ ├─┬ gauge@2.7.4 
  │   │   │ │ ├── aproba@1.1.1 
  │   │   │ │ ├── has-unicode@2.0.1 
  │   │   │ │ ├── object-assign@4.1.1 
  │   │   │ │ ├── signal-exit@3.0.2 
  │   │   │ │ ├─┬ string-width@1.0.2 
  │   │   │ │ │ ├── code-point-at@1.1.0 
  │   │   │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │   │   │ │ │   └── number-is-nan@1.0.1 
  │   │   │ │ ├─┬ strip-ansi@3.0.1 
  │   │   │ │ │ └── ansi-regex@2.1.1 
  │   │   │ │ └── wide-align@1.1.2 
  │   │   │ └── set-blocking@2.0.0 
  │   │   ├─┬ rc@1.2.1 
  │   │   │ ├── deep-extend@0.4.2 
  │   │   │ ├── ini@1.3.4 
  │   │   │ ├── minimist@1.2.0 
  │   │   │ └── strip-json-comments@2.0.1 
  │   │   ├─┬ request@2.81.0 
  │   │   │ ├── aws-sign2@0.6.0 
  │   │   │ ├── aws4@1.6.0 
  │   │   │ ├── caseless@0.12.0 
  │   │   │ ├─┬ combined-stream@1.0.5 
  │   │   │ │ └── delayed-stream@1.0.0 
  │   │   │ ├── extend@3.0.1 
  │   │   │ ├── forever-agent@0.6.1 
  │   │   │ ├─┬ form-data@2.1.4 
  │   │   │ │ └── asynckit@0.4.0 
  │   │   │ ├─┬ har-validator@4.2.1 
  │   │   │ │ ├─┬ ajv@4.11.8 
  │   │   │ │ │ ├── co@4.6.0 
  │   │   │ │ │ └─┬ json-stable-stringify@1.0.1 
  │   │   │ │ │   └── jsonify@0.0.0 
  │   │   │ │ └── har-schema@1.0.5 
  │   │   │ ├─┬ hawk@3.1.3 
  │   │   │ │ ├── boom@2.10.1 
  │   │   │ │ ├── cryptiles@2.0.5 
  │   │   │ │ ├── hoek@2.16.3 
  │   │   │ │ └── sntp@1.0.9 
  │   │   │ ├─┬ http-signature@1.1.1 
  │   │   │ │ ├── assert-plus@0.2.0 
  │   │   │ │ ├─┬ jsprim@1.4.0 
  │   │   │ │ │ ├── assert-plus@1.0.0 
  │   │   │ │ │ ├── extsprintf@1.0.2 
  │   │   │ │ │ ├── json-schema@0.2.3 
  │   │   │ │ │ └── verror@1.3.6 
  │   │   │ │ └─┬ sshpk@1.13.0 
  │   │   │ │   ├── asn1@0.2.3 
  │   │   │ │   ├── assert-plus@1.0.0 
  │   │   │ │   ├── bcrypt-pbkdf@1.0.1 
  │   │   │ │   ├─┬ dashdash@1.14.1 
  │   │   │ │   │ └── assert-plus@1.0.0 
  │   │   │ │   ├── ecc-jsbn@0.1.1 
  │   │   │ │   ├─┬ getpass@0.1.7 
  │   │   │ │   │ └── assert-plus@1.0.0 
  │   │   │ │   ├── jodid25519@1.0.2 
  │   │   │ │   ├── jsbn@0.1.1 
  │   │   │ │   └── tweetnacl@0.14.5 
  │   │   │ ├── is-typedarray@1.0.0 
  │   │   │ ├── isstream@0.1.2 
  │   │   │ ├── json-stringify-safe@5.0.1 
  │   │   │ ├─┬ mime-types@2.1.15 
  │   │   │ │ └── mime-db@1.27.0 
  │   │   │ ├── oauth-sign@0.8.2 
  │   │   │ ├── performance-now@0.2.0 
  │   │   │ ├── qs@6.4.0 
  │   │   │ ├── safe-buffer@5.0.1 
  │   │   │ ├── stringstream@0.0.5 
  │   │   │ ├─┬ tough-cookie@2.3.2 
  │   │   │ │ └── punycode@1.4.1 
  │   │   │ ├── tunnel-agent@0.6.0 
  │   │   │ └── uuid@3.0.1 
  │   │   ├─┬ rimraf@2.6.1 
  │   │   │ └─┬ glob@7.1.2 
  │   │   │   ├── fs.realpath@1.0.0 
  │   │   │   ├── inflight@1.0.6 
  │   │   │   ├─┬ minimatch@3.0.4 
  │   │   │   │ └─┬ brace-expansion@1.1.7 
  │   │   │   │   ├── balanced-match@0.4.2 
  │   │   │   │   └── concat-map@0.0.1 
  │   │   │   └── path-is-absolute@1.0.1 
  │   │   ├── semver@5.3.0 
  │   │   ├─┬ tar@2.2.1 
  │   │   │ ├── block-stream@0.0.9 
  │   │   │ ├─┬ fstream@1.0.11 
  │   │   │ │ └── graceful-fs@4.1.11 
  │   │   │ └── inherits@2.0.3 
  │   │   └─┬ tar-pack@3.4.0 
  │   │     ├─┬ debug@2.6.8 
  │   │     │ └── ms@2.0.0 
  │   │     ├── fstream-ignore@1.0.5 
  │   │     ├─┬ once@1.4.0 
  │   │     │ └── wrappy@1.0.2 
  │   │     ├─┬ readable-stream@2.2.9 
  │   │     │ ├── buffer-shims@1.0.0 
  │   │     │ ├── core-util-is@1.0.2 
  │   │     │ ├── isarray@1.0.0 
  │   │     │ ├── process-nextick-args@1.0.7 
  │   │     │ ├── string_decoder@1.0.1 
  │   │     │ └── util-deprecate@1.0.2 
  │   │     └── uid-number@0.0.6 
  │   ├── glob-parent@2.0.0 
  │   ├─┬ is-binary-path@1.0.1 
  │   │ └── binary-extensions@1.10.0 
  │   ├─┬ is-glob@2.0.1 
  │   │ └── is-extglob@1.0.0 
  │   └─┬ readdirp@2.1.0 
  │     ├─┬ readable-stream@2.3.3 
  │     │ ├── isarray@1.0.0 
  │     │ └── string_decoder@1.0.3 
  │     └── set-immediate-shim@1.0.1 
  └─┬ yargs@8.0.2 
    ├── camelcase@4.1.0 
    ├─┬ cliui@3.2.0 
    │ ├─┬ string-width@1.0.2 
    │ │ ├── code-point-at@1.1.0 
    │ │ └─┬ is-fullwidth-code-point@1.0.0 
    │ │   └── number-is-nan@1.0.1 
    │ ├─┬ strip-ansi@3.0.1 
    │ │ └── ansi-regex@2.1.1 
    │ └─┬ wrap-ansi@2.1.0 
    │   └── string-width@1.0.2 
    ├── decamelize@1.2.0 
    ├── get-caller-file@1.0.2 
    ├─┬ os-locale@2.1.0 
    │ ├─┬ execa@0.7.0 
    │ │ ├─┬ cross-spawn@5.1.0 
    │ │ │ ├─┬ shebang-command@1.2.0 
    │ │ │ │ └── shebang-regex@1.0.0 
    │ │ │ └─┬ which@1.3.0 
    │ │ │   └── isexe@2.0.0 
    │ │ ├── get-stream@3.0.0 
    │ │ ├── is-stream@1.1.0 
    │ │ ├─┬ npm-run-path@2.0.2 
    │ │ │ └── path-key@2.0.1 
    │ │ ├── p-finally@1.0.0 
    │ │ ├── signal-exit@3.0.2 
    │ │ └── strip-eof@1.0.0 
    │ ├─┬ lcid@1.0.0 
    │ │ └── invert-kv@1.0.0 
    │ └─┬ mem@1.1.0 
    │   └── mimic-fn@1.1.0 
    ├─┬ read-pkg-up@2.0.0 
    │ ├─┬ find-up@2.1.0 
    │ │ └─┬ locate-path@2.0.0 
    │ │   ├─┬ p-locate@2.0.0 
    │ │   │ └── p-limit@1.1.0 
    │ │   └── path-exists@3.0.0 
    │ └─┬ read-pkg@2.0.0 
    │   ├─┬ load-json-file@2.0.0 
    │   │ ├─┬ parse-json@2.2.0 
    │   │ │ └─┬ error-ex@1.3.1 
    │   │ │   └── is-arrayish@0.2.1 
    │   │ ├── pify@2.3.0 
    │   │ └── strip-bom@3.0.0 
    │   ├─┬ normalize-package-data@2.4.0 
    │   │ ├── hosted-git-info@2.5.0 
    │   │ ├─┬ is-builtin-module@1.0.0 
    │   │ │ └── builtin-modules@1.1.1 
    │   │ └─┬ validate-npm-package-license@3.0.1 
    │   │   ├─┬ spdx-correct@1.0.2 
    │   │   │ └── spdx-license-ids@1.2.2 
    │   │   └── spdx-expression-parse@1.0.4 
    │   └── path-type@2.0.0 
    ├── require-directory@2.1.1 
    ├── require-main-filename@1.0.1 
    ├── set-blocking@2.0.0 
    ├─┬ string-width@2.1.1 
    │ ├── is-fullwidth-code-point@2.0.0 
    │ └─┬ strip-ansi@4.0.0 
    │   └── ansi-regex@3.0.0 
    ├── which-module@2.0.0 
    ├── y18n@3.2.1 
    └─┬ yargs-parser@7.0.0 
      └── camelcase@4.1.0

**Comment by hansonw** [comment]
Wait, you should not be installing Hyperclick from source. Please remove your `git clone` version and just use APM to install Hyperclick:

```
rm -rf ~/.atom/packages/hyperclick
apm install hyperclick
```

**Comment by zzgzhang** [comment]
As you words, tried apm way.restart atom but still not work

============================================
zzg-mbp:~ zzg$ rm -rf ~/.atom/packages/hyperclick
zzg-mbp:~ zzg$ apm install hyperclick
Installing hyperclick to /Users/zzg/.atom/packages ✓
zzg-mbp:~ zzg$

**Comment by hansonw** [comment]
I don't know when js-hyperclick is supposed to activate... Can you try a
simpler provider like `hyperlink-hyperclick`?

https://atom.io/packages/hyperlink-hyperclick

**Comment by zzgzhang** [comment]
Thanks , as i mentioned above, i have my .atom/package folder clear but only hyperclick reinstalled just now by apm.
And hyperclick is supposed to activate such as find var defination in single file (while js-hyperclick will support between files based on hyperclick)

**Comment by hansonw** [comment]
No, actually Hyperclick does not provide *any* functionality out of the box. You must install providers like `hyperlink-hyperclick`, `js-hyperclick`, etc. for it to do anything.

**Comment by zzgzhang** [comment]
Duang!!!

It works fine now, both hyperlink-hyperclick and js-hyperclick.
Perhaps apm did right thing rather than git clone. Learned.

Thanks for your great job. Good day!
