### ISSUE TITLE
Settings break on atom restart requiring plugin reinstall

### ISSUE THREAD

**Issue by epelc** [facebooknuclide/hyperclick#44]
Whenever atom restarts with hyperclick installed the plugin breaks `cmd+click` multi cursor functionality. The settings for `hyperclick` look like they break(showing as inputs instead of selects). The only fix I've found is to reinstall hyperclick every time you open atom which is becoming very annoying.

## Settings after restarting atom
multicursor and hyperclick are not working at this point.
![image](https://user-images.githubusercontent.com/5204642/35287094-987d3528-002f-11e8-85ac-d94c3bd90fbf.png)

## After reinstalling hyperclick(fix)
![image](https://user-images.githubusercontent.com/5204642/35287144-b25082ac-002f-11e8-9172-aaf222f49654.png)

**Comment by epelc** [comment]
I just figured out that this happens only when `facebook-atom/atom-ide-ui` is also installed.

**Comment by hansonw** [comment]
You don't need both of these. Hyperclick is deprecated in favour of just using `atom-ide-ui`, which bundles it (I'll update the docs to reflect this.)
